# Generated by Django 3.2 on 2022-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0003_auto_20220415_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
