# Generated by Django 3.2 on 2022-04-18 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0004_auto_20220415_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
