# Generated by Django 3.2 on 2022-04-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0005_remove_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
