# Generated by Django 3.2 on 2022-04-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0006_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(default='uk', max_length=20),
            preserve_default=False,
        ),
    ]
