# Generated by Django 3.2 on 2022-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250, null=True)),
                ('user_slug', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('fax', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('year_of_business', models.CharField(max_length=4)),
                ('solo', models.TextField()),
                ('partnership', models.TextField()),
                ('corporation', models.TextField()),
                ('other', models.TextField()),
                ('tax', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[(1, 'Highly Dissatisfied'), (2, 'Dissatified'), (3, 'Nutral'), (4, 'Satisfied'), (5, 'Highly Satisfied')], max_length=10)),
                ('review', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(max_length=10)),
                ('date', models.DateField(null=True)),
                ('in_time', models.DateTimeField()),
                ('out_time', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('text_field', models.TextField()),
                ('break_time', models.TextField(null=True)),
                ('wages', models.CharField(max_length=10, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('pending', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('time_sheet', models.BooleanField(default=False)),
            ],
        ),
    ]
