# Generated by Django 3.2 on 2022-04-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='corporation',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='companyinfo',
            name='solo',
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='Partnership',
            field=models.CharField(choices=[(1, 'Solo Proprietorship'), (2, 'Partnership'), (3, 'Corporation')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='about_company',
            field=models.TextField(null=True),
        ),
    ]
