# Generated by Django 3.2 on 2022-04-18 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0003_auto_20220415_1843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinfo',
            old_name='Partnership',
            new_name='partnership',
        ),
    ]
