# Generated by Django 3.2 on 2022-04-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0004_rename_partnership_companyinfo_partnership'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift_post',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-04-12'),
            preserve_default=False,
        ),
    ]
