# Generated by Django 3.2 on 2022-04-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_web', '0005_shift_post_update_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='partnership',
            field=models.CharField(choices=[(1, 'Solo Proprietorship'), (2, 'Partnership'), (3, 'Corporation'), (4, 'Other')], max_length=10, null=True),
        ),
    ]
