"""
Django settings for staff_hiring project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# from employee_web.views import *
import requests


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s$qfh%(_9ve2+bg@wy_%_!!se!f^+j)1dmywirm516-=6=@qcb"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "192.168.1.249",
    "carenet.devtechnosys.tech",
    "0.0.0.0",
    "127.0.0.1",
    "localhost",
    '192.168.1.181',
]
CSRF_TRUSTED_ORIGINS = ["https://carenet.devtechnosys.tech"]

# Application definition

INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "staff_admin",
    "staff_app",
    "employee_web",
    "applicant_web",
    "rest_framework.authtoken",
    "django_twilio",
    "safedelete",
    "chatapp",
    "sslserver",
    "django.contrib.sites",
    "django_extensions",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.facebook",
    "allauth.socialaccount.providers.google",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "staff_admin.middlewares.login_middleware",
    # "employee_web.middlewares.check_middleware",
]

ROOT_URLCONF = "staff_hiring.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

SOCIALACCOUNT_PROVIDERS = {
    "facebook": {
        "METHOD": "js_sdk",
        "SCOPE": ["email", "public_profile"],
        "FIELDS": ["id", "email", "name", "first_name", "last_name", "verified"],
    }
}


SOCIAL_AUTH_FACEBOOK_KEY = "1388282428280767"  # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = "2e7405ba05cb475724058605cc436607"  # app key
# SITE_ID = 2


# ASGI_APPLICATION = 'staff_hiring.asgi.application'
WSGI_APPLICATION = "staff_hiring.wsgi.application"
AUTH_USER_MODEL = "staff_admin.User"


AUTHENTICATION_BACKENDS = [
    # 'django.contrib.auth.backends.ModelBackend',
    "allauth.account.auth_backends.AuthenticationBackend"
]
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    # 'allauth.account.auth_backends.AuthenticationBackend'
]
SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
    }
}


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'STAFF_HIRING',
#         'USER': 'root',
#         'PASSWORD': 'Admin@123',
#         'HOST': 'localhost',   # Or an IP Address that your DB is hosted on
#         'PORT': '3306',
#     }
# }


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SITE_ID = 1
SOCIALACCOUNT_PROVIDERS = {"facebook": {}, "google": {}}


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = (
    "918001596774-5ga21m03da0oi4a95r8jqqqrldhacf7o.apps.googleusercontent.com"
)
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "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"
SOCIALACCOUNT_LOGIN_ON_GET = True

AUTH_USER_MODEL = "staff_admin.User"


LOGIN_URL = "/accounts/google/login/callback/"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"


# ACCOUNT_ADAPTER = 'staff_hiring.adapter.DisableSignupAdapter'

# project/users/allauth.py:


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Asia/Calcutta"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")

REST_FRAMEWORK = {
    "DATETIME_FORMAT": "%m-%d-%Y %H:%M:%S",
}

# social()

# STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "carenet761@gmail.com"
EMAIL_HOST_PASSWORD = "care761@net"
# EMAIL_HOST_USER = "hotbuttonin@gmail.com"
# EMAIL_HOST_PASSWORD = "261117@Shivay"

SMS_BACKEND = "sms.backends.twilio.SmsBackend"
TWILIO_ACCOUNT_SID = "AC019fd98eb93a0c0398699add4be2610b"
TWILIO_AUTH_TOKEN = "5bb7104e6601007289a62bc6b6b6b8ab"
TWILIO_NUMBER = "+19285758419"

SAFE_DELETE_INTERPRET_UNDELETED_OBJECTS_AS_CREATED = True

# ROOT_URLCONF = 'chatapp.urls'
# Channels

ASGI_APPLICATION = "staff_hiring.asgi.application"
# CHANNEL_LAYERS = {
#     'default': {
#         "BACKEND": "channels.layers.InMemoryChannelLayer"
#     },
# }


CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
