# Generated by Django 3.2 on 2022-04-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDeatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccinated', models.CharField(max_length=100)),
                ('first_dose', models.DateField(default='2022-03-01')),
                ('second_dose', models.DateField(default='2022-03-01')),
                ('image', models.ImageField(blank=True, default='face1.jpg', null=True, upload_to='vaccination')),
                ('booster_dose', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250, null=True)),
                ('nmc_pin', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('recitation', models.BooleanField()),
                ('recitation_desc', models.TextField(null=True)),
                ('enhance_dbc', models.CharField(max_length=150, null=True)),
                ('enhance_dbc_issue', models.DateField(null=True)),
                ('dbc_status', models.CharField(max_length=150, null=True)),
                ('work_checkes', models.TextField(null=True)),
                ('work_preference', models.TextField(null=True)),
                ('emergency_no', models.CharField(max_length=20, null=True)),
                ('training_start_date', models.DateField(null=True)),
                ('training_end_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[(1, 'APPORVE'), (2, 'QUERY'), (3, 'PENDING')], default=3, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('time_in', models.TimeField(null=True)),
                ('time_out', models.TimeField(null=True)),
                ('break_time', models.CharField(max_length=6, null=True)),
                ('authorized_by', models.CharField(max_length=100, null=True)),
                ('approve_date', models.DateField(null=True)),
                ('approved_by', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[(1, 'APPORVE'), (2, 'REJECT'), (3, 'PENDING')], default=3, max_length=10)),
                ('applicant_review', models.TextField(null=True)),
                ('sign_img', models.ImageField(default='face1.jpg', upload_to='signature')),
                ('submit_status', models.BooleanField(default=False)),
                ('employee_review', models.TextField(null=True)),
                ('rating', models.CharField(choices=[(1, 'SO-WOREST'), (2, 'WOREST'), (3, 'GOOD'), (4, 'VERY GOOD'), (5, 'EXCELLENT')], default=3, max_length=10, null=True)),
            ],
        ),
    ]
