# Generated by Django 3.2 on 2022-04-07 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_web', '0001_initial'),
        ('applicant_web', '0001_initial'),
        ('staff_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='app_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_position', to='staff_admin.category'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_sheet_applicant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='emp_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_position', to='staff_admin.category'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_sheet_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='shift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_web.shift_post'),
        ),
        migrations.AddField(
            model_name='shiftlike',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_like', to='employee_web.shift_post'),
        ),
        migrations.AddField(
            model_name='shiftlike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querymessage',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant_web.query'),
        ),
        migrations.AddField(
            model_name='query',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='query',
            name='postion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='query_position', to='staff_admin.category'),
        ),
        migrations.AddField(
            model_name='query',
            name='timesheet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant_web.timesheet'),
        ),
        migrations.AddField(
            model_name='applicantdeatails',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_info_position', to='staff_admin.category'),
        ),
        migrations.AddField(
            model_name='applicantdeatails',
            name='training',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_admin.training'),
        ),
        migrations.AddField(
            model_name='applicantdeatails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
