# Generated by Django 3.2 on 2022-04-07 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant_web', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='querymessage',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querymessage',
            name='message',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='querymessage',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='querymessage',
            name='reciver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qurery_message_reciever', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='querymessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qurery_message_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
