# Generated by Django 3.2 on 2022-04-07 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant_web', '0004_auto_20220407_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='applicant_review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approve_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='approved_by',
            field=models.CharField(default='20222-04-04', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_sheet_employee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='employee_review',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='rating',
            field=models.CharField(choices=[(1, 'SO-WOREST'), (2, 'WOREST'), (3, 'GOOD'), (4, 'VERY GOOD'), (5, 'EXCELLENT')], default=3, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='sign_img',
            field=models.ImageField(default='face1.jpg', upload_to='signature'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='status',
            field=models.CharField(choices=[(1, 'APPORVE'), (2, 'REJECT'), (3, 'PENDING')], default=3, max_length=10),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='submit_status',
            field=models.BooleanField(default=False),
        ),
    ]
