# Generated by Django 3.2 on 2022-04-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_web', '0005_auto_20220407_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querymessage',
            name='name',
        ),
        migrations.AddField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='resolve_status',
            field=models.BooleanField(default=False),
        ),
    ]
