# Generated by Django 3.2 on 2022-04-18 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_web', '0006_auto_20220415_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantdeatails',
            old_name='nmc_pin',
            new_name='Mnc_pin',
        ),
    ]
