# Generated by Django 3.2 on 2022-04-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_web', '0007_rename_nmc_pin_applicantdeatails_mnc_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-14'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timesheet',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, default='2022-04-14'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicantdeatails',
            name='Mnc_pin',
            field=models.CharField(max_length=100, verbose_name='Mnc pin'),
        ),
    ]
