# Generated by Django 3.2 on 2022-04-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_web', '0008_auto_20220419_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantdeatails',
            name='vaccination_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
